#!/bin/bash
#-------------------------------------------------------
#
# bootstrapping utility for autotools 
#
# ------------------------------------------------------

cmd="autoreconf -f -i"
echo "Bootstrapping using $cmd ..."

$cmd
